apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: efs-claim
 namespace: elastic-job
spec:
 storageClassName: efs-sc
 resources:
   requests:
     storage: 60Gi
 accessModes:
    - ReadWriteMany